version: '3'

services:
  web:
    container_name: web-udw-local
    build:
      context: ./app
    networks:
      - udw-local
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
      - web-static-local:/usr/src/app/static
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python manage.py runserver 0.0.0.0:1234"


  nginx:
    container_name: nginx-udw-local
    image: nginx:latest
    depends_on:
      - web
    ports:
      - ${HGINX_PORT:-8000}:9000
    volumes:
      - web-static-local:/usr/src/app/static
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - udw-local

  db:
    container_name: db-udw-local
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db-udw-local:/var/lib/postgresql/data/
    ports:
      - ${LOCAL_POSTGRES_PORT:-5432}:5432
    networks:
      - udw-local

volumes:
  web-static-local:
  db-udw-local:

networks:
  udw-local:
    driver: bridge
